//EVALUATE Customer
//EVALUATE VALUES ( Customer[City] )
//EVALUATE
//CALCULATETABLE ( Customer, Customer[City] = "Redmond" )
//EVALUATE
//CALCULATETABLE ( VALUES ( Customer[City] ), LEFT ( Customer[City], 1 ) = "R" )
//EVALUATE
//CALCULATETABLE ( VALUES ( Customer[City] ), LEFT ( Customer[City], 1 ) = "R" )
//ORDER BY Customer[City]
//
//DEFINE
//    MEASURE Sales[My Sales Amount] =
//        SUM ( Sales[Sales Amount] )
//EVALUATE
//ADDCOLUMNS ( VALUES ( 'Date'[Month] ), "My Sales Amount", [My Sales Amount] )
//
//DEFINE
//    MEASURE Sales[My Sales Amount] = SUM ( Sales[Sales Amount] )
//    MEASURE Sales[My Double Sales Amount] = SUM ( Sales[Sales Amount] ) * 2
//EVALUATE
//ADDCOLUMNS (
//    VALUES ( 'Date'[Month] ),
//    "My Sales Amount", [My Sales Amount],
//    "My Double Sales Amount", [My Double Sales Amount]
//)

//EVALUATE
//{ SUM ( Sales[Sales Amount] ) }
//EVALUATE
//SUM ( Sales[Sales Amount] )

//DEFINE
//    MEASURE Sales[Total Sales] =
//        SUM ( Sales[Sales Amount] )
//EVALUATE
//{ [Total Sales] }

//
//EVALUATE
//SUMMARIZECOLUMNS (
//    Product[Color],
//    Reseller[Business Type],
//    FILTER ( ALL ( 'Product'[List Price] ), 'Product'[List Price] > 150.00 ),
//    TREATAS ( { "Accessories", "Bikes" }, 'Product'[Category] ),
//    "Total Sales", SUM ( Sales[Sales Amount] )
//)

//DEFINE
//    MEASURE Sales[Total Sales] =
//        SUM ( Sales[Sales Amount] )
//    MEASURE Sales[Total Cost] =
//        SUMX ( Sales, Sales[Unit Price] * Sales[Order Quantity] )
//EVALUATE
//{ [Total Sales] }
//EVALUATE
//{ [Total Cost] }

//
//EVALUATE
//FILTER ( 'Product', 'Product'[Color] = @Color )